## MySQL
## Spring Boot configures Hibernate as the default JPA provider
## Spring Boot-1, the default connection pool was Tomcat, but it has been changed to HikariCP with Spring Boot-2
spring:
  application:
    name: ctc-dms
jwt:
  secret: ${jwtsecret}

azure:
  keyvault:
    enabled: true
    uri: https://smkeyvault1.vault.azure.net/
  cosmos:
    uri: https://dms-cosmo.documents.azure.com:443/
    key: LJwToJCn9emYeDF7b3CXu9xDmdYbUE6bt7gbi0Ch1BKXjp8fHj5bPoZXfefbLCA63UihXoc4ObuPQGyivO8maA==
    database: dms-cosmo-db
    populateQueryMetrics: true

custom:
  repo: cosmo
  	