apiVersion: v1
kind: Service
metadata:
    name: "dmscluster-e709"
    labels:
        app: "dmscluster-e709"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dmscluster-e709"